// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNtuE0UlWVPXS_TqacdAKQgmz3S_oqhXY',
    appId: '1:610649629212:web:91fcba45d5d9823daa75d9',
    messagingSenderId: '610649629212',
    projectId: 'armakeupapp',
    authDomain: 'armakeupapp.firebaseapp.com',
    storageBucket: 'armakeupapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaV7BDdvbSLHrhVdG26y4au8kpZ430N4o',
    appId: '1:610649629212:android:fd8fb7c305b04477aa75d9',
    messagingSenderId: '610649629212',
    projectId: 'armakeupapp',
    storageBucket: 'armakeupapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYwdcaWpC97nwxO7f3QisTYdEFogvDX5g',
    appId: '1:610649629212:ios:61fa1e7ea7fff27eaa75d9',
    messagingSenderId: '610649629212',
    projectId: 'armakeupapp',
    storageBucket: 'armakeupapp.firebasestorage.app',
    iosBundleId: 'com.example.arMakeupApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYwdcaWpC97nwxO7f3QisTYdEFogvDX5g',
    appId: '1:610649629212:ios:61fa1e7ea7fff27eaa75d9',
    messagingSenderId: '610649629212',
    projectId: 'armakeupapp',
    storageBucket: 'armakeupapp.firebasestorage.app',
    iosBundleId: 'com.example.arMakeupApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNtuE0UlWVPXS_TqacdAKQgmz3S_oqhXY',
    appId: '1:610649629212:web:2d143e939bf9f357aa75d9',
    messagingSenderId: '610649629212',
    projectId: 'armakeupapp',
    authDomain: 'armakeupapp.firebaseapp.com',
    storageBucket: 'armakeupapp.firebasestorage.app',
  );
}
